services:
  django_app:
    build:
      context: ./django_clerk
      dockerfile: Dockerfile.dev
    volumes:
      - ./django_clerk/src:/app
    env_file:
      - .env
      - .env.backend.local
    ports:
      - "8888:8888"
      
  nodejs_app:
    #image: node:lts-slim
    #image: node:lts-slim
    build:
      context: ./nextjs_clerk
      dockerfile: Dockerfile.dev
    volumes:
      - ./nextjs_clerk/public:/app/public
      - ./nextjs_clerk/src:/app/src
      - ./nextjs_clerk/package.json:/app/package.json
      - ./nextjs_clerk/jsonfig.json:/app/jsonfig.json
      - ./nextjs_clerk/next.config.mjs:/app/next.config.mjs
      - ./nextjs_clerk/postcss.config.mjs:/app/postcss.config.mjs

    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    develop:
      watch:
        - action: rebuild
          path: nextjs_clerk/Dockerfile.dev
        - action: rebuild
          path: nextjs_clerk/package.json

    env_file:
      - .env
      - .env.nextjs.local

  react_app:
    #image: node:lts-slim
    build:
      context: ./react_clerk
      dockerfile: Dockerfile.dev
    volumes:
      - ./react_clerk/index.html:/app/index.html
      - ./react_clerk/src:/app/src
      - ./react_clerk/public:/app/public
    ports:
      - 5173:5173
    env_file:
      - .env
    #working_dir: /app/react_clerk/index.html:/app/index.html

  fastapi_app:
    build:
      context: ./fastapi_clerk
      dockerfile: Dockerfile.dev
    volumes:
      - ./fastapi_clerk/src:/app
    env_file:
      - .env
      - .env.backend.local
    ports:
      - "8002:8002"
