FROM python:3.13.3-bullseye

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY ./src /app/
COPY ./requirements.txt /tmp/requirements.txt

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
ENV PYTHONUNBUFFERED=1

EXPOSE 8888

CMD ["python", "manage.py", "runserver", "0.0.0.0:8888"]
